// Package agentkit is an agent loop as a library: a provider, Go tools and
// MCP servers, with no files and no global state. The Agent holds what is
// costly; each Conversation holds its own history.
package agentkit

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ThiraSoft/agentkit/llm"
	"github.com/ThiraSoft/agentkit/mcp"
)

const (
	defaultMaxSteps      = 20
	defaultMaxToolResult = 32 << 10
)

// Config describes an agent. ProviderImpl, if non-nil, overrides
// Provider, Model, BaseURL, APIKey and the provider options below
// (Temperature, MaxTokens, PromptCache, ResponseSchema).
type Config struct {
	Provider string // "gemini", "openai-compat", "anthropic", "llamacpp"...
	Model    string
	BaseURL  string // full base URL of provider, e.g. https://generativelanguage.googleapis.com/v1beta for Gemini, http://host:port/v1 for an OpenAI-compatible server (empty = default)
	APIKey   string // empty = provider environment variable

	// Temperature, when set, is the sampling temperature. Some models refuse
	// it (recent Anthropic ones, OpenAI reasoning models).
	Temperature *float64
	// MaxTokens caps the tokens generated by one model call; 0 leaves the
	// provider's default (32000 for Anthropic, which requires a value).
	MaxTokens int
	// PromptCache asks the provider to cache the prompt where it has to be
	// told (Anthropic); see Turn.Usage for what was read from the cache.
	PromptCache bool
	// ResponseSchema, when set, is a JSON Schema (an object) the model's
	// answers must follow; SchemaFor writes one from a Go type, and the
	// answer is the text of the last message of the history (Turn.Text too
	// when no tool ran). Not every model takes it together with tools.
	ResponseSchema json.RawMessage

	ProviderImpl llm.Provider

	Tools []Tool
	MCP   []mcp.ServerConfig

	MaxSteps      int // model calls per Send, 20 by default
	MaxToolResult int // bytes kept from a tool result, 32 KB by default
}

// Tool is a tool executed in the caller's process. Run must respect
// ctx cancellation: cancellation waits for tools to finish.
// A panic in Run is recovered and reported to the model as an error.
type Tool struct {
	Name        string
	Description string
	Parameters  llm.ToolParams
	// Schema is a JSON Schema of the arguments, an object. When set, it
	// replaces Parameters, and can say what Parameters cannot: enums,
	// nested objects, bounds. NewTool writes it from a Go type.
	Schema json.RawMessage
	Run    func(ctx context.Context, args json.RawMessage) (string, error)
}

// Agent brings together a provider and tools. It holds no conversation state
// and serves multiple Conversations concurrently.
type Agent struct {
	provider      llm.Provider
	defs          []llm.Tool
	local         map[string]Tool
	remote        map[string]bool
	manager       *mcp.Manager
	maxSteps      int
	maxToolResult int
}

// New builds the provider, connects MCP servers and validates tools.
// It fails rather than falling back to something else.
func New(ctx context.Context, cfg Config) (*Agent, error) {
	if len(cfg.ResponseSchema) > 0 {
		if err := objectSchema(cfg.ResponseSchema); err != nil {
			return nil, fmt.Errorf("agentkit: ResponseSchema: %w", err)
		}
	}
	provider := cfg.ProviderImpl
	if provider == nil {
		p, err := llm.NewProvider(llm.Config{
			Provider:       llm.ProviderType(cfg.Provider),
			Model:          cfg.Model,
			BaseURL:        cfg.BaseURL,
			APIKey:         cfg.APIKey,
			Temperature:    cfg.Temperature,
			MaxTokens:      cfg.MaxTokens,
			PromptCache:    cfg.PromptCache,
			ResponseSchema: cfg.ResponseSchema,
		})
		if err != nil {
			return nil, fmt.Errorf("agentkit: %w", err)
		}
		provider = p
	}
	a := &Agent{
		provider:      provider,
		local:         map[string]Tool{},
		remote:        map[string]bool{},
		maxSteps:      cfg.MaxSteps,
		maxToolResult: cfg.MaxToolResult,
	}
	if a.maxSteps <= 0 {
		a.maxSteps = defaultMaxSteps
	}
	if a.maxToolResult <= 0 {
		a.maxToolResult = defaultMaxToolResult
	}

	for _, t := range cfg.Tools {
		if t.Name == "" || t.Run == nil {
			return nil, fmt.Errorf("agentkit: tool %q has no name or no Run func", t.Name)
		}
		if _, dup := a.local[t.Name]; dup {
			return nil, fmt.Errorf("agentkit: tool %q is declared twice", t.Name)
		}
		if len(t.Schema) > 0 {
			if err := objectSchema(t.Schema); err != nil {
				return nil, fmt.Errorf("agentkit: tool %q: %w", t.Name, err)
			}
		}
		a.local[t.Name] = t
		a.defs = append(a.defs, llm.Tool{
			Type: "function",
			Function: llm.FunctionDef{
				Name:        t.Name,
				Description: t.Description,
				Parameters:  t.Parameters,
				Schema:      t.Schema,
			},
		})
	}

	if len(cfg.MCP) > 0 {
		m := mcp.NewManager(cfg.MCP)
		if err := m.Connect(ctx); err != nil {
			m.Close()
			return nil, fmt.Errorf("agentkit: %w", err)
		}
		for _, def := range m.GetToolDefinitions() {
			name := def.Function.Name
			if _, dup := a.local[name]; dup || a.remote[name] {
				m.Close()
				return nil, fmt.Errorf("agentkit: tool %q is declared twice", name)
			}
			a.remote[name] = true
			a.defs = append(a.defs, def)
		}
		a.manager = m
	}
	return a, nil
}

// Tools returns the tool names seen by the model, in the order it sees
// them: Go tools first, then MCP servers.
func (a *Agent) Tools() []string {
	names := make([]string, len(a.defs))
	for i, d := range a.defs {
		names[i] = d.Function.Name
	}
	return names
}

// Close disconnects MCP servers.
func (a *Agent) Close() error {
	if a.manager != nil {
		return a.manager.Close()
	}
	return nil
}
